"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { AdminShell } from "@/components/admin/admin-shell";
import { Button, Card, CardBody, Input } from "@/components/ui/index";
import { supabase } from "@/lib/supabase";

export default function AdminCouponsPage() { const client = useQueryClient(); const [code, setCode] = useState(""); const [value, setValue] = useState("10"); const query = useQuery({ queryKey: ["admin-coupons-edit"], queryFn: async () => { const { data, error } = await supabase.from("coupons").select("*").order("created_at", { ascending: false }); if (error) throw error; return data as { id: string; code: string; discount_type: string; discount_value: number; is_active: boolean }[]; } }); async function createCoupon() { if (!code.trim()) return; await supabase.from("coupons").insert({ code: code.trim().toUpperCase(), description: `${value}% off`, discount_type: "percent", discount_value: Number(value), min_order_amount: 0, is_active: true }); setCode(""); client.invalidateQueries({ queryKey: ["admin-coupons-edit"] }); } return <AdminShell><Card><CardBody><h2 className="font-black text-stone-900">Create coupon</h2><div className="mt-3 flex flex-wrap gap-2"><Input className="max-w-48" placeholder="WELCOME10" value={code} onChange={(event) => setCode(event.target.value)} /><Input className="max-w-32" type="number" min="1" value={value} onChange={(event) => setValue(event.target.value)} /><Button onClick={createCoupon}>Create</Button></div></CardBody></Card><Card><CardBody className="divide-y divide-stone-100 p-0">{query.data?.map((coupon) => <div key={coupon.id} className="flex items-center justify-between gap-3 p-4"><div><p className="font-bold text-stone-900">{coupon.code}</p><p className="text-sm text-stone-500">{coupon.discount_value}{coupon.discount_type === "percent" ? "%" : " INR"} · {coupon.is_active ? "Active" : "Inactive"}</p></div><Button size="sm" variant={coupon.is_active ? "secondary" : "primary"} onClick={async () => { await supabase.from("coupons").update({ is_active: !coupon.is_active }).eq("id", coupon.id); client.invalidateQueries({ queryKey: ["admin-coupons-edit"] }); }}>{coupon.is_active ? "Deactivate" : "Activate"}</Button></div>)}</CardBody></Card></AdminShell>; }
